config/routes.rb
Delusion::Application.routes.draw do
  	devise_for :users

    match '/graphicslinear',    :to => 'home#graphicslinear'
	  match '/graphicspie',       :to => 'home#graphicspie'
 	  match '/graphicscolumns',   :to => 'home#graphicscolumns'
	  match '/graphicsarea',      :to => 'home#graphicsarea'
	  match '/graphs',            :to => 'home#graphs'
  	
	  root :to => "home#index"
end

app/models/acidag.rb
class Acidag < ActiveRecord::Base
end

app/models/acidagalert.rb
class Acidagalert < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/intrusion.rb
class Intrusion < ActiveRecord::Base
end

app/models/iphdr.rb
class Iphdr < ActiveRecord::Base
end

app/models/search.rb
class Search < ActiveRecord::Base
	attr_accessible :tipo, :date, :user_id, :atributos

	belongs_to :user

	validates :tipo, :presence => true,
					 :length   => { :within => 4..40 }

	validates :user_id, :presence => true

end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
end

app/models/sigclass.rb
class Sigclass < ActiveRecord::Base
end

app/models/signature.rb
class Signature < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :searches, :dependent => :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!
  
  private	
  
  def after_sign_out_path_for(resource_or_scope)	
    scope = Devise::Mapping.find_scope!(resource_or_scope)	
    send(:"new_#{scope}_session_path")    	
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @user = current_user
  	@searches = Search.all
  end
  
  def graphs
    @users = User.all
    @user = current_user
    @intrusions = Intrusion.all
  	@intrusionsAttribs = Intrusion.columns_hash
  	@searches = Search.all
  end
  
  def graphicspie
    @users = User.all
    @user = current_user
	  save_search("Pie Chart")
	  @searches = Search.all
  end

  def graphicscolumns
    @users = User.all
    @user = current_user
	  save_search("Column Chart")
	  @searches = Search.all
  end

  def graphicsarea
    @users = User.all
    @user = current_user
	  save_search("Area Chart")
	  @searches = Search.all
  end

  def graphicslinear
    @users = User.all  
    @user = current_user
	  save_search("Linear Chart")
	  @searches = Search.all
  end

  private
    def save_search (tipo)
	  provse = Search.new
	  provse.tipo = tipo
	  provse.date = Time.now.to_datetime
	  provse.user_id = current_user.id
	  provse.atributos = "none"
	  provse.save
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_sidebar.html.erb
<script type="text/javascript">
$(document).ready(function(){
	$("#clicame").click(function(){ $("#bnn2").slideToggle(); });
});

$(document).ready(function(){
	$("#escondido-1").click(function(){ $("#escondido-0").slideToggle(); });
});
</script>

<div class="block notice">
  <h3>News</h3>
  <div class="content">
    <p>Hello, <%= @user.email %></p>
	<a id="clicame">hide/show last searches</a>
  </div>
</div>

<div id="bnn2" class="block notice">
  <table id="hor-minimalist-a" summary="last search sheet">
    <thead>
	  <th scope="col">Type</th>
	  <th scope="col">Date</th>
	  <th scope="col">User</th>
	  <th scope="col"></th>
	</thead>
	<tbody>
	<% @searches.last(10).each do |s| %>
	  <tr>
		<td><%= s.tipo %></td>
		<td><%= s.date %></td>
		<td><%= s.user_id %></td>
		<td><%= link_to 'show', root_path %></td>
	  </tr>
	<% end %>
	</tbody>	
  </table>
</div>

<div class="block">
  <h3>Search</h3>
  <ul class="navigation">
    <li><%= link_to 'Tables', root_path %></li>
    <li> <%= link_to 'Graphs', graphs_path %> </li>
  </ul>
</div>

app/views/home/graficos.html.erb
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<%= javascript_include_tag "graficos/highcharts.js" %>
<%= javascript_include_tag "graficos/modules/exporting.js" %>

<script type="text/javascript">
	var chart;
	$(document).ready(function() {
		chart = new Highcharts.Chart({
			chart: {
				renderTo: 'contentor', 
				defaultSeriesType: 'scatter',
				zoomType: 'xy'
			},
			title: {
				text: 'Acess'
			},
			xAxis: {
				title: {
					enabled: true,
					text: 'Time'
				},
				startOnTick: true,
				endOnTick: true,
				showLastLabel: true
			},
			yAxis: {
				title: {
					text: 'Danger (0-10)'
				}
			},
	
			//Info quando se passa o rato por cima do ponto
			tooltip: {
				backgroundColor: '#FCFFC5',
				style: {
					    padding: 5,
						fontSize: '10px'
				},
				formatter: function() {
            		    return 'Time: ' + Math.floor(this.x) + 'h ' 
						+ Math.round((this.x%1)*60) + 'm' 
						+ '<br />Danger: <b>' + this.y + '</b><br />' + 
						'<a href="' + this.series.name + '">Click for details</a>';// + '<br />' + <%= @user.email %>;
				}  
			},
			legend: {
				layout: 'vertical',
				align: 'left',
				verticalAlign: 'top',
				x: 48,
				y: 10,
				floating: true,
				backgroundColor: '#FFFFFF',
				borderWidth: 1
			},
			plotOptions: {
				scatter: {
					marker: {
						radius: 5,
						states: {
							hover: {
								enabled: true,
								lineColor: 'rgb(100,100,100)'
							}
						}
					},
					states: {
						hover: {
							marker: {
								enabled: false
							}
						}
					}
				}
			},
			series: [{
				name: '195.234.134.174',
				color: 'rgba(223, 83, 83, .5)',
				data: [[1.2, 6.0], [7.5, 9.0], [9.5, 9.0], [7.0, 3.0], [5.1, 3.0], 
					[17.0, 9.0], [15.1, 7.0], [16.0, 6.0], [17.2, 8.0], [16.2, 7.0], 
					[17.5, 5.0], [22.2, 2.0], [21.9, 5.0], [15.4, 2.0], [16.0, 5.0], 
					]		
			}, {
				name: '129.42.38.1',
				color: 'rgba(119, 152, 191, .5)',
				data: [[4.0, 5.0], [17.3, 1.0], [19.5, 8.0], [18.5, 2.0], [18.2, 8.0], 
					[22.5, 4.0], [14.0, 6.0], [14.5, 1.0], [15.0, 2.0], [18.0, 1.0], 
					]
			}, {
		        name: '213.15.0.3',
		        color: 'rgba(118, 244, 118, .5)',
		        data: [[4.0, 1.0], [17.3, 7.0], [19.5, 3.0], [18.5, 2.0], [18.2, 6.0], 
		            [22.5, 6.0], [22.0, 5.0], [14.5, 4.0], [15.0, 3.0], [18.0, 1.0], 
		            ]
			}, {
			    name: '209.85.169.105',
			    color: 'rgba(228, 255, 0, .5)',
			    data: [[3.2, 2.0], [12.3, 1.0], [7.5, 3.0], [1.5, 2.0], [10.2, 2.0], 
			        [22.5, 3.0], [5.2, 2.0], [3.5, 1.0], [8.0, 2.0], [9.3, 1.0], 
					]
			}, {
			    name: '69.171.229.11',
			    color: 'rgba(54, 54, 54, .5)',
				data: [[2.2, 5.0], [3.3, 1.0], [4.4, 8.0], [5.5, 2.0], [6.6, 2.0], 
				    [10.5, 6.0], [17.0, 6.0], [22.5, 6.0], [23.0, 2.0], [21.0, 1.0],
					]
			}
			]
		});
	});
</script>

<div class="block" id="block-text">  
  <div class="content">
  	<h2> Linear charts! </h2>
	<div class="inner" >
		<div id="contentor" style=" width: 70%; height: 400px; margin: 0 auto;"></div>
	</div>
	<div class="inner" style=" width: 90%; height: 120px; margin: 0 auto; margin-bottom:15px;">
			<div id=caixas class="nice_border" >
				<input type="checkbox" id="checkbox-1"/><label for="checkbox-1">Ip Origem</label> 
				<input type="checkbox" id="checkbox-2"/><label for="checkbox-2">Port</label> 
				<input type="checkbox" id="checkbox-3"/><label for="checkbox-3">Danger</label> 
				<input type="checkbox" id="checkbox-4"/><label for="checkbox-4">Ip Dest</label> 
				<input type="checkbox" id="checkbox-5"/><label for="checkbox-5">TCP</label> 
				<input type="checkbox" id="checkbox-6"/><label for="checkbox-6">UDP</label> 
				<input type="checkbox" id="checkbox-7"/><label for="checkbox-7">ICMP</label> 
				<input type="checkbox" id="checkbox-8"/><label for="checkbox-8">New</label> 
				<input type="checkbox" id="checkbox-9"/><label for="checkbox-9">Bb</label> 
				<input type="checkbox" id="checkbox-0"/><label for="checkbox-0">Xyz</label> 
			</div>
			<div id=botao class="nice_border" >
				<input type="button" value="load graph"/>
			</div>
	</div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/home/graphicsarea.html.erb
<script type="text/javascript">
var chart;
$(document).ready(function() {
   chart = new Highcharts.Chart({
      chart: {
         renderTo: 'contentor', 
         defaultSeriesType: 'area'
      },
      title: {
         text: 'US and USSR nuclear stockpiles'
      },
      subtitle: {
         text: 'Source: <a href="http://thebulletin.metapress.com/content/c4120650912x74k7/fulltext.pdf">'+'thebulletin.metapress.com</a>'
      },
      xAxis: {
         labels: {
            formatter: function() {
               return this.value; // clean, unformatted number for year
            }
         }                     
      },
      yAxis: {
         title: {
            text: 'Nuclear weapon states'
         },
         labels: {
            formatter: function() {
               return this.value / 1000 +'k';
            }
         }
      },
      tooltip: {
         formatter: function() {
            return this.series.name +' produced <b>'+
               Highcharts.numberFormat(this.y, 0) +'</b><br/>warheads in '+ this.x;
         }
      },
      plotOptions: {
         area: {
            pointStart: 1940,
            marker: {
               enabled: false,
               symbol: 'circle',
               radius: 2,
               states: {
                  hover: {
                     enabled: true
                  }
               }
            }
         }
      },
      series: [{
         name: 'USA',
         data: [null, null, null, null, null, 6 , 11, 32, 110, 235, 369, 640, 
            1005, 1436, 2063, 3057, 4618, 6444, 9822, 15468, 20434, 24126, 
            27387, 29459, 31056, 31982, 32040, 31233, 29224, 27342, 26662, 
            26956, 27912, 28999, 28965, 27826, 25579, 25722, 24826, 24605, 
            24304, 23464, 23708, 24099, 24357, 24237, 24401, 24344, 23586, 
            22380, 21004, 17287, 14747, 13076, 12555, 12144, 11009, 10950, 
            10871, 10824, 10577, 10527, 10475, 10421, 10358, 10295, 10104 ]
      }, {
         name: 'USSR/Russia',
         data: [null, null, null, null, null, null, null , null , null ,null, 
         5, 25, 50, 120, 150, 200, 426, 660, 869, 1060, 1605, 2471, 3322, 
         4238, 5221, 6129, 7089, 8339, 9399, 10538, 11643, 13092, 14478, 
         15915, 17385, 19055, 21205, 23044, 25393, 27935, 30062, 32049, 
         33952, 35804, 37431, 39197, 45000, 43000, 41000, 39000, 37000, 
         35000, 33000, 31000, 29000, 27000, 25000, 24000, 23000, 22000, 
         21000, 20000, 19000, 18000, 18000, 17000, 16000]
      }]
   });
});
</script>

<div class="block" id="block-text">  
  <div class="content">
  	<h2> Linear charts! </h2>
	<div class="inner" >
		<div id="contentor" style=" width: 70%; height: 400px; margin: 0 auto;"></div>
	</div>
	<div class="inner" style=" width: 90%; height: 120px; margin: 0 auto; margin-bottom:15px;">
			<div id=caixas class="nice_border" >
				<input type="checkbox" id="checkbox-1"/><label for="checkbox-1">Ip Origem</label> 
				<input type="checkbox" id="checkbox-2"/><label for="checkbox-2">Port</label> 
				<input type="checkbox" id="checkbox-3"/><label for="checkbox-3">Danger</label> 
				<input type="checkbox" id="checkbox-4"/><label for="checkbox-4">Ip Dest</label> 
				<input type="checkbox" id="checkbox-5"/><label for="checkbox-5">TCP</label> 
				<input type="checkbox" id="checkbox-6"/><label for="checkbox-6">UDP</label> 
				<input type="checkbox" id="checkbox-7"/><label for="checkbox-7">ICMP</label> 
				<input type="checkbox" id="checkbox-8"/><label for="checkbox-8">New</label> 
				<input type="checkbox" id="checkbox-9"/><label for="checkbox-9">Bb</label> 
				<input type="checkbox" id="checkbox-0"/><label for="checkbox-0">Xyz</label> 
			</div>
			<div id=botao class="nice_border" >
				<input type="button" value="load graph"/>
			</div>
	</div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/home/graphicscolumns.html.erb
<script type="text/javascript">
	var chart;

	$(document).ready(function() {
		chart = new Highcharts.Chart({
			chart: {
				renderTo: 'contentor',
				defaultSeriesType: 'column'
			},
	
			title: {
				text: 'Average Danger Level'
			},
			
			subtitle: {
				text: 'Subtitle'
			},

			xAxis: {
				categories: [
					'IPs' 
				]
			},

			yAxis: {
				min: 0,
				title: {
					text: 'Danger (0-10)'
				}
			},
			
			tooltip: {
				style: {
					padding: 5,
					fontSize: '10px'
				},
				
				formatter: function() {
					return 'IP: ' + this.series.name + '<br />'
					+ 'Danger: <b>' + this.y + '</b><br />'
					+ '<a href="' + this.series.name + '">Click for details</a>';
				},
			},

			legend: {
				enabled: false
			},
		

			plotOptions: {
				column: {
					pointPadding: 0.2,
					borderWidth: 0
				}
			},
	
			series: [
				{
					name: '195.234.134.174',
					data: [7.1]
				}, {
					name: '129.42.38.1',
					data: [3.2]
				}, {
					name: '213.15.0.3',
					data: [4.1]
				}, {
					name: '209.85.169.105',
					data: [2.8]
				}, {
					name: '69.171.229.11',
					data: [9.3]
				}
			]
		});
	});
</script>

<div class="block" id="block-text">  
  <div class="content">
  	<h2> Column Charts! </h2>
	<div class="inner" >
		<div id="contentor" style=" width: 70%; height: 400px; margin: 0 auto;"></div>
	</div>
	<div class="inner" style=" width: 90%; height: 120px; margin: 0 auto; margin-bottom:15px;">
			<div id=caixas class="nice_border" >
				<input type="checkbox" id="checkbox-1"/><label for="checkbox-1">Ip Origem</label> 
				<input type="checkbox" id="checkbox-2"/><label for="checkbox-2">Port</label> 
				<input type="checkbox" id="checkbox-3"/><label for="checkbox-3">Danger</label> 
				<input type="checkbox" id="checkbox-4"/><label for="checkbox-4">Ip Dest</label> 
				<input type="checkbox" id="checkbox-5"/><label for="checkbox-5">TCP</label> 
				<input type="checkbox" id="checkbox-6"/><label for="checkbox-6">UDP</label> 
				<input type="checkbox" id="checkbox-7"/><label for="checkbox-7">ICMP</label> 
				<input type="checkbox" id="checkbox-8"/><label for="checkbox-8">New</label> 
				<input type="checkbox" id="checkbox-9"/><label for="checkbox-9">Bb</label> 
				<input type="checkbox" id="checkbox-0"/><label for="checkbox-0">Xyz</label> 
			</div>
			<div id=botao class="nice_border" >
				<input type="button" value="load graph"/>
			</div>
	</div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/home/graphicslinear.html.erb
<script type="text/javascript">
	var chart;
	$(document).ready(function() {
		chart = new Highcharts.Chart({
			chart: {
				renderTo: 'contentor', 
				defaultSeriesType: 'scatter',
				zoomType: 'xy'
			},
			title: {
				text: 'Acess'
			},
			xAxis: {
				title: {
					enabled: true,
					text: 'Time'
				},
				startOnTick: true,
				endOnTick: true,
				showLastLabel: true
			},
			yAxis: {
				title: {
					text: 'Danger (0-10)'
				}
			},
	
			//Info quando se passa o rato por cima do ponto
			tooltip: {
				backgroundColor: '#FCFFC5',
				style: {
					    padding: 5,
						fontSize: '10px'
				},
				formatter: function() {
            		    return 'Time: ' + Math.floor(this.x) + 'h ' 
						+ Math.round((this.x%1)*60) + 'm' 
						+ '<br />Danger: <b>' + this.y + '</b><br />' + 
						'<a href="' + this.series.name + '">Click for details</a>';
				}  
			},
			legend: {
				align: 'center',
				verticalAlign: 'bottom',
				backgroundColor: '#FFFFFF',
				borderWidth: 1
			},
			plotOptions: {
				scatter: {
					marker: {
						radius: 5,
						states: {
							hover: {
								enabled: true,
								lineColor: 'rgb(100,100,100)'
							}
						}
					},
					states: {
						hover: {
							marker: {
								enabled: false
							}
						}
					}
				}
			},
			series: [{
				name: '195.234.134.174',
				color: 'rgba(223, 83, 83, .5)',
				data: [[1.2, 6.0], [7.5, 9.0], [9.5, 9.0], [7.0, 3.0], [5.1, 3.0], 
					[17.0, 9.0], [15.1, 7.0], [16.0, 6.0], [17.2, 8.0], [16.2, 7.0], 
					[17.5, 5.0], [22.2, 2.0], [21.9, 5.0], [15.4, 2.0], [16.0, 5.0], 
					]		
			}, {
				name: '129.42.38.1',
				color: 'rgba(119, 152, 191, .5)',
				data: [[4.0, 5.0], [17.3, 1.0], [19.5, 8.0], [18.5, 2.0], [18.2, 8.0], 
					[22.5, 4.0], [14.0, 6.0], [14.5, 1.0], [15.0, 2.0], [18.0, 1.0], 
					]
			}, {
		        name: '213.15.0.3',
		        color: 'rgba(118, 244, 118, .5)',
		        data: [[4.0, 1.0], [17.3, 7.0], [19.5, 3.0], [18.5, 2.0], [18.2, 6.0], 
		            [22.5, 6.0], [22.0, 5.0], [14.5, 4.0], [15.0, 3.0], [18.0, 1.0], 
		            ]
			}, {
			    name: '209.85.169.105',
			    color: 'rgba(228, 255, 0, .5)',
			    data: [[3.2, 2.0], [12.3, 1.0], [7.5, 3.0], [1.5, 2.0], [10.2, 2.0], 
			        [22.5, 3.0], [5.2, 2.0], [3.5, 1.0], [8.0, 2.0], [9.3, 1.0], 
					]
			}, {
			    name: '69.171.229.11',
			    color: 'rgba(54, 54, 54, .5)',
				data: [[2.2, 5.0], [3.3, 1.0], [4.4, 8.0], [5.5, 2.0], [6.6, 2.0], 
				    [10.5, 6.0], [17.0, 6.0], [22.5, 6.0], [23.0, 2.0], [21.0, 1.0],
					]
			}
			]
		});
	});
</script>

<div class="block" id="block-text">  
  <div class="content">
  	<h2> Linear charts! </h2>
	<div class="inner" >
		<div id="contentor" style=" width: 70%; height: 400px; margin: 0 auto;"></div>
	</div>
	<div class="inner" style=" width: 90%; height: 120px; margin: 0 auto; margin-bottom:15px;">
			<div id=caixas class="nice_border" >
				<input type="checkbox" id="checkbox-1"/><label for="checkbox-1">Ip Origem</label> 
				<input type="checkbox" id="checkbox-2"/><label for="checkbox-2">Port</label> 
				<input type="checkbox" id="checkbox-3"/><label for="checkbox-3">Danger</label> 
				<input type="checkbox" id="checkbox-4"/><label for="checkbox-4">Ip Dest</label> 
				<input type="checkbox" id="checkbox-5"/><label for="checkbox-5">TCP</label> 
				<input type="checkbox" id="checkbox-6"/><label for="checkbox-6">UDP</label> 
				<input type="checkbox" id="checkbox-7"/><label for="checkbox-7">ICMP</label> 
				<input type="checkbox" id="checkbox-8"/><label for="checkbox-8">New</label> 
				<input type="checkbox" id="checkbox-9"/><label for="checkbox-9">Bb</label> 
				<input type="checkbox" id="checkbox-0"/><label for="checkbox-0">Xyz</label> 
			</div>
			<div id=botao class="nice_border" >
				<input type="button" value="load graph"/>
			</div>
	</div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/home/graphicspie.html.erb
<script type="text/javascript">
	var chart;
	
	$(document).ready(function() {
		chart = new Highcharts.Chart({
			chart: {
				renderTo: 'contentor',
				plotBackgroundColor: null,
				plotBorderWidth: null,
				plotShadow: false
			},

			title: {
				text: 'Port access'
			},
			
			tooltip: {
				formatter: function() {
					return '<b>'+ this.point.name +'</b>: '+ this.percentage +' %';
				}
			},
				
			plotOptions: {
				pie: {
					allowPointSelect: true,
					cursor: 'pointer',
					
					dataLabels: {
						enabled: true,
						color: '#000000',
						connectorColor: '#000000',
						formatter: function() {
							return '<b>'+ this.point.name +'</b>: '+ Highcharts.numberFormat(this.percentage, 1) +'%';
						}
					}
				}
			},
			
			series: [{
				type: 'pie',
				name: 'Browser share',
				data: [
						['80',   45.0],
						['22',       26.0],
						{   name: '3128',    
							y: 12.8,
							sliced: true,
							selected: true
						},
						['20',    5.0],
						['443',     6.0],
						['1080',    5.0],
						['Others',    10]
				]
			}]
		});
	});
</script>

<div class="block" id="block-text">  
  <div class="content">
  	<h2> Pie Charts! </h2>
	<div class="inner" >
		<div id="contentor" style=" width: 70%; height: 400px; margin: 0 auto;"></div>
	</div>
	<div class="inner" style=" width: 90%; height: 120px; margin: 0 auto; margin-bottom:15px;">
			<div id=caixas class="nice_border" >
				<input type="checkbox" id="checkbox-1"/><label for="checkbox-1">Ip Origem</label> 
				<input type="checkbox" id="checkbox-2"/><label for="checkbox-2">Port</label> 
				<input type="checkbox" id="checkbox-3"/><label for="checkbox-3">Danger</label> 
				<input type="checkbox" id="checkbox-4"/><label for="checkbox-4">Ip Dest</label> 
				<input type="checkbox" id="checkbox-5"/><label for="checkbox-5">TCP</label> 
				<input type="checkbox" id="checkbox-6"/><label for="checkbox-6">UDP</label> 
				<input type="checkbox" id="checkbox-7"/><label for="checkbox-7">ICMP</label> 
				<input type="checkbox" id="checkbox-8"/><label for="checkbox-8">New</label> 
				<input type="checkbox" id="checkbox-9"/><label for="checkbox-9">Bb</label> 
				<input type="checkbox" id="checkbox-0"/><label for="checkbox-0">Xyz</label> 
			</div>
			<div id=botao class="nice_border" >
				<input type="button" value="load graph"/>
			</div>
	</div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/home/graphs.html.erb
<div class="block" id="block-text">  
  <div class="content">
  	<h2> Graphs </h2>
	<div class="inner" id="submitcheck">
	  <form class="formbox">
	    <% @intrusionsAttribs.each do |key,value| %>
	      <% if value.name != "id" %>
	      <% if value.name != "created_at" %> 
	      <% if value.name != "updated_at" %>
	      <div class="radio">
		     <%= radio_button_tag "attrib_name", value.name %>
		     <%= label_tag value.name %>
		  </div>
		  <% end %>
		  <% end %>
		  <% end %>
		<% end %>
	  </form>
	</div>
	
	<div class="inner">
		<div id="rendergraph">
		</div>
	</div>
	
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

<script type="text/javascript">
	var chart;
	var rvalue = $(":checked").val();
	$(':radio').click(function() {
		chart = new Highcharts.Chart({
			chart: {
				marginRight: 30,
				marginBottom: 100,
				spacingTop: 30,
				renderTo: 'rendergraph',
				backgroundColor: '#FFFFFF',
				shadow: true,
				defaultSeriesType: 'column',
				zoomType: 'xy'
			},
			credits: {
		        enabled: false
		    },
			legend: {
				layout: 'vertical',
				align: 'center',
				verticalAlign: 'bottom',
				backgroundColor: '#FFFFFF',
				borderWidth: 1
			},
			title: {
				text: 'Graph'
			},
			xAxis: {
				title: {
					enabled: true,
					text: $(":checked").val()
				}
			},
			yAxis: {
				title: {
					text: 'Alert'
				}
			},
			series:[{
				data: [
				  <% @intrusions.each do |int| %>
				  [<%= int.id %>, <%=int.alert %>],
				  <% end %>
				]
			}]
		});
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Delusion HoneyPot</title>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
  <%= stylesheet_link_tag "web_app_theme" %>
  <%= javascript_include_tag "graficos/highcharts", "graficos/modules/exporting" %>
  <%= csrf_meta_tag %>
  <link rel="shortcut icon" href="favicon.ico" />
</head>
<body>
  <div id="container">
    <div id="header">
	  <a href="http://localhost:3000" title="Delusion Home">
		<%= image_tag("web-app-theme/themes/default/images/delusionLogo.png", :size => "280x85") %>
	  </a>
      <h1><%= link_to 'Delusion HoneyPot', root_path %></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <li><%= link_to t("web-app-theme.profile", :default => "Profile"), root_path %></li>
          <li><%= link_to t("web-app-theme.settings", :default => "Settings"), root_path %></li>
          <li><%= link_to t("web-app-theme.logout", :default => "Logout"), destroy_user_session_path %></li>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf"></ul>
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> Delusion HoneyPot.</p>
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>